# Generated by Django 4.2.1 on 2023-10-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matrikel_number', models.IntegerField()),
                ('experiment_number', models.CharField(max_length=10)),
                ('report', models.FileField(upload_to='reports/')),
                ('raw_data', models.FileField(upload_to='raw_data/')),
                ('date_of_submission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
