# Generated by Django 4.2.1 on 2023-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_experimentdata_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='matrikel_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadline',
            name='semester',
            field=models.CharField(choices=[('summer_2023', 'Summer 2023'), ('fall_2023', 'Fall 2023'), ('summer_2024', 'Summer 2024'), ('fall_2024', 'Fall 2024')], default='summer_2023', max_length=20),
        ),
    ]
